### PR TITLE
Add ability to set Faraday request options

### PR DESCRIPTION
**Pull request by Jhowden**
We would like to add a timeout to the Faraday requests. This adds a default timeout of 30 seconds with the ability to override it by passing in a map.

### CODE REVIEW

**Comment by jboltz88** [comment]
@Jhowden I have no problem merging this, but we need to have the failing specs resolved first.

**Comment by Jhowden** [comment]
Updated!

**Comment by Jhowden** [comment]
@jboltz88 Did you need me to bump the gem version so that it cuts a new release of the gem or is that something you will be doing on your end?

**Comment by jboltz88** [comment]
@Jhowden I'll take care of it when I push it to rubygems.org. Thanks for the contribution!

**Pull request merged**
